name: Upload and Download Artifacts

on:
  push:
    branches:
      - main

jobs:
  uploadartifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files in public directory
        run: ls -la public  # This will show the contents of the public directory
        
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: artifactfile3
          path: public  # Correct path to the directory you want to upload

  downloadartifacts:
    runs-on: ubuntu-latest
    needs: uploadartifacts
    steps:
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: artifactfile3
          path: public  # Correct path where you want to download the artifact
