name: Share data between jobs
on: push
jobs:
  job_1:
    name: Upload  File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files in public directory
        run: ls -la public  # This will show the contents of the public directory
      - run: echo "Hello World" > file.txt
      - uses: actions/upload-artifact@main
        with:
          name: file
          path: public/file.txt

  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@main
        with:
          name: file
      - run: cat public/file.txt
