name: Label Approved Pull Requests

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@main
        env:
          APPROVALS: "1"  # Number of approvals required to add the label
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          ADD_LABEL: "approved"  # Label to be added
