name: "call compositeaction"

on:
  push:
    branches:
      - main
jobs:
  callingcompossiteaction:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: ./github/my-actions
        with:
          node-version: '18'
  
