name: "Hello Actions"
on:
  push:
    branches:
      - main

jobs:
  greet:  # Define a job named 'greet'
    runs-on: ubuntu-latest  # Specify the environment to run the job
    steps:
      - name: Run Docker Action
        uses: ./  # Use the action defined in the current repository
