name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"
on:
  push:
    branches:
      - main

jobs:
  greet:  # Define a job named 'greet'
    runs-on: ubuntu-latest  # Specify the environment to run the job
    steps:
      - name: Run Docker Action
        uses: .  # Use the action defined in the current repository

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
