name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"
on:push

inputs:
    MY_NAME:
      description: "Who to greet"
      required: true
      default: "World"

runs:
    uses: "docker"
    image: "Dockerfile"

branding:
    icon: "mic"
    color: "purple"
