name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"
on:
  push: 
    - main

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker" # Corrected from 'uses' to 'using'
  image: "Dockerfile" # Ensure Dockerfile is in the correct location

branding:
  icon: "mic"
  color: "purple"
