name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"
on:
  push:
    branches:
      - main  # Correctly specify the branch under 'branches'

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker" # Correct usage for Docker actions
  image: "Dockerfile" # Ensure Dockerfile is in the correct location

branding:
  icon: "mic"
  color: "purple"
