name: "Default Environment variables"
on:
  push:
    branches:
      - main
jobs:
  envvariables:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: step1
      - run: echo "Deploying to production server on branch $GITHUB_REF"
