name: "Expression Workflow"
on:
  [push, pull_request]

jobs:
  checkexpression:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Event Type"
        run: |
          echo "the event name is ${{github.event_name}}"
          
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "This is a ${{github.event_name}} event aq"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "This is a pull request event"
          fi

      - name: "Check Event Type Dynamically"
        run: |
          EVENT_NAME="${{ github.event_name }}"
          if [ "$EVENT_NAME" = "push" ]; then
            echo "This is a push event"
            echo "This is a $EVENT_NAME event aq2"
          elif [ "$EVENT_NAME" = "pull_request" ]; then
            echo "This is a pull request event"
          fi
