name:"node.js workflow"
on:
  push:
    branches:
      - main
jobs:
  buildnode.js:
  runs-on: ubuntu-latest:
  strategy:
    matrix:
      node-version:[14.x,16.x,18.x]
  steps:
   - name:"node instalation version ${{matrix.node-version}}"
   - uses: actions/checkout@v3
     uses: actions/setup-node@v3
     with:
       node-version: ${{matrix.node-version}}
       cache:'npm'
    - run :npm ci
    -run: npm run build --if-present
    -run:npm test
    
