name: "script as action"
on:
  push:
    branches:
      - main

jobs:
  runbatsoftwareasruncommand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code
      - name: step1
        run: npm install -g bats
